### ISSUE TITLE
Broken scroll after applying dataProvider filter

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-grid-flow#123]
Grid scroll is broken when grid has dataProvider and ComponentRenderer column and some filter is applied to the dataProvider.

Prerequisites:
vaadin-grid (1.0.0.beta3, but it was reproduced earlier as well)
ComponentRenderer (flow 1.0.0.beta2)
Tried browsers:
Chrome: no exceptions
Firefox: `TypeError: a is null`

Simple example: https://github.com/alexberazouski/skeleton-starter-flow-spring/tree/bug/grid-scroll

1. Open localhost:8080
2. Scroll the grid 2-3 page down
3. Check SetFilter checkbox
4. Scroll grid again

See that grid always returns back the scroll to the initial position

Bug is not reproduced if grid doesn't have the ComponentRenderer column.

**Comment by alexberazouski** [comment]
Please add the app-starter label

**Comment by pekam** [comment]
It seems that this is not specific to filtering. This happens every time when you change the items in the grid, **if the amount of items is changing**. And yes, it's specific to `ComponentRenderer`.

For example, when I first set the `ListDataProvider` with int values 1-100, and then set a new `ListDataProvider` with items 101-200, everything works. But if I set a `ListDataProvider` with items 101-199, or 101-201, the bug occurs.

I also discovered another similar bug:
If you change the amount of items to a really low number, like if you have items 1-100, scroll down, and then set items to 1-3, you get:
`TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'`
So this also happens when you change the items after scrolling down, but it happens even if you're not using `ComponentRenderer` so it might be a separate issue.

**Comment by pekam** [comment]
[This line in `flow-grid-component-renderer`](https://github.com/vaadin/vaadin-grid-flow/blob/a73630add07fa34478cce074b14d1b60726c5b74/src/main/resources/META-INF/resources/frontend/flow-grid-component-renderer.html#L49) causes infinite loop after scrolling down and changing the items. It asynchronously calls `grid.notifyResize()` and for some reason that causes the `onComponentRendered` to be called again, causing the loop.

**Comment by pekam** [comment]
So the `flow-grid-component-renderer`s just keep getting new node-ids infinitely:
```
nodeid change: 600 -> 612
nodeid change: 602 -> 614
nodeid change: 604 -> 616
nodeid change: 606 -> 618
nodeid change: 608 -> 620
nodeid change: 610 -> 622
nodeid change: 612 -> 624
nodeid change: 614 -> 626
nodeid change: 616 -> 628
nodeid change: 618 -> 630
nodeid change: 620 -> 632
nodeid change: 622 -> 634
nodeid change: 624 -> 636
nodeid change: 626 -> 638
nodeid change: 628 -> 640
nodeid change: 640 -> 590
nodeid change: 638 -> 588
nodeid change: 636 -> 586
nodeid change: 634 -> 584
nodeid change: 632 -> 582
nodeid change: 630 -> 580
nodeid change: 580 -> 592
nodeid change: 582 -> 594
nodeid change: 584 -> 596
nodeid change: 586 -> 598
nodeid change: 588 -> 600
nodeid change: 590 -> 602
nodeid change: 592 -> 604
nodeid change: 594 -> 606
nodeid change: 596 -> 608
nodeid change: 598 -> 610
nodeid change: 600 -> 612     <--- here it loops
nodeid change: 602 -> 614
nodeid change: 604 -> 616
nodeid change: 606 -> 618
...
```
