### ISSUE TITLE
Support Grid's million pixel scrolling

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid-flow#14]
@Legioth commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2501)

`<vaadin-grid>` adds its own virtual scrolling on top of the API that is carried over from `<iron-list>`. This means that the `_virtualStart` and `_virtualEnd` variables by themselves are not reliable when scrolling beyond a certain threshold, but should additionally also be offset by `_vidxOffset`. This variable is initially 0, but will have non-zero values when scrolled far enough to risk triggering overflows in the `scrollTop` property that e.g. `_virtualStart` is based on.

---

@pleku commented on [Wed Oct 18 2017](https://github.com/vaadin/flow/issues/2501#issuecomment-337481006)

@Legioth please clarify what this should achieve ? Removal of `size()` query from the Lazy DataProviders ?

---

@Legioth commented on [Wed Oct 18 2017](https://github.com/vaadin/flow/issues/2501#issuecomment-337483246)

The terminology here is slightly confusing. Making `size()` optional is "infinite" scrolling, whereas the feature here is just scrolling beyond limits natively supported by the DOM.

The Grid element works around limitations to the maximum supported `scrollTop` value in different browsers by introducing a "virtual" scrollTop, reseting the actual DOM property to a value within the acceptable range and manually managing the scrollbar to make it look like the user is really scrolled somewhere else. Once this happens, `_virtualStart` and `_virtualEnd` will no longer on their own contain the right values, but in addition the `_vidxOffset` property also needs to be taken into account.

**Comment by Artur-** [comment]
This really needs to be fixed as it causes the server to OOM pretty much instantly if you have a huge data set.

Given a grid with 1,000,000 rows, the initial rendering asks the data provider for:
```
Fetching 0 - 49
Fetching 50 - 99
```
which is ok. Scrolling to the end asks the data provider for:
```
Fetching 99850 - 999999
```
which is wrong that it will quite quickly cause an OOM on the server (loading 900K rows for each user)

If you increase the data set to 10,000,000 rows, you will load 9M rows instead of 0.9M rows in memory for each user.

There is no way that you can take this into account when developing your app, it is always just a disaster in production when the data set has grown.
