### ISSUE TITLE
SPIKE: Add API for appending & prepending header & footer rows

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#147]
The API should be similar to FW 7 and 8 Grid where adding a row means that it will get all of the columns. 
Because the web component works very differently compared to the widget, this is basically just an abstraction layer that maps to column groups.

Here is the example for appending and prepending headers and adding a footer row for FW 8 (from sampler grid basic features):

```java
HeaderRow topHeader = grid.prependHeaderRow();
 
grid.addColumn(CompanyBudgetHistory::getCompany)
            .setId("CompanyNameColumn")
            .setCaption("Company");
 
// Create a DecimalFormat for later use in column renderers and captions
// that should display values as currency, dollars in this case
DecimalFormat dollarFormat = new DecimalFormat("$#,##0.00");
 
IntStream.range(baseYear, baseYear + numberOfYears).forEach(year -> {
 
        Column<?, ?> firstHalfColumn = grid.addColumn(
                budgetHistory -> budgetHistory.getFirstHalfOfYear(year),
                new NumberRenderer(dollarFormat))
                .setStyleGenerator(budgetHistory -> "align-right")
                .setId(year + "H1").setCaption("H1");
 
        Column<?, ?> secondHalfColumn = grid.addColumn(
                budgetHistory -> budgetHistory.getSecondHalfOfYear(year),
                new NumberRenderer(dollarFormat))
                .setStyleGenerator(budgetHistory -> "align-right")
                .setId(year + "H2").setCaption("H2");
 
        topHeader.join(firstHalfColumn, secondHalfColumn)
                .setText(year + "");
});
 
// Add a summary footer row to the Grid
FooterRow footer = grid.appendFooterRow();
// Update the summary row every time data has changed
// by collecting the sum of each column's data
grid.getDataProvider().addDataProviderListener(event -> {
 
        List<CompanyBudgetHistory> data = event.getSource()
                .fetch(new Query<>()).collect(Collectors.toList());
 
        IntStream.range(baseYear, baseYear + numberOfYears)
                .forEach(year -> {
 
                    BigDecimal firstHalfSum = data.stream()
                            .map(budgetHistory -> budgetHistory.getFirstHalfOfYear(year))
                            .reduce(BigDecimal.ZERO, BigDecimal::add);
 
                    BigDecimal secondHalfSum = data.stream()
                            .map(budgetHistory -> budgetHistory.getSecondHalfOfYear(year))
                            .reduce(BigDecimal.ZERO, BigDecimal::add);
 
                    footer.getCell(year + "H1")
                            .setText(dollarFormat.format(firstHalfSum));
                    footer.getCell(year + "H2")
                            .setText(dollarFormat.format(secondHalfSum));
                });
});
...
 
private void setColumnFiltering(boolean filtered) {
    if (filtered && filteringHeader == null) {
        filteringHeader = sample.appendHeaderRow();
 
        // Add new TextFields to each column which filters the data from
        // that column
        TextField filteringField = getColumnFilterField();
        filteringField.addValueChangeListener(event -> {
            dataProvider.setFilter(CompanyBudgetHistory::getCompany, company -> {
                if (company == null) {
                    return false;
                }
                String companyLower = company.toLowerCase(Locale.ENGLISH);
                String filterLower = event.getValue().toLowerCase(Locale.ENGLISH);
                return companyLower.contains(filterLower);
            });
        });
        filteringHeader.getCell("CompanyNameColumn")
                .setComponent(filteringField);
    } else if (!filtered && filteringHeader != null) {
        dataProvider.clearFilters();
        sample.removeHeaderRow(filteringHeader);
        filteringHeader = null;
    }
}
```

**Comment by pleku** [comment]
Related to #59 and #120. After this this issue, we should be able to say how we resolve those, by basically either:
- adding the API that makes it easy and fixes #120 
- just fixing #120 and adding better docs and examples for #59

**Comment by pekam** [comment]
Because of the hierarchical structure of columns in `<vaadin-grid>`, the amount of cells in a `HeaderRow` can not increase upwards. Some implications of this:
- A new prepended `HeaderRow` will have the same amount of `HeaderCells` as the previously top-most `HeaderRow` (the same cells are joined)
- We can allow joining `HeaderCells` only on the top-most `HeaderRow`
  - or we can automatically join all the cells on top of the joined ones, and then the user would have to re-set the content also for the automatically joined cells

**Comment by pekam** [comment]
My original approach for appending `HeaderRows` to the bottom was:
- wrap the column inside a column-group
- move the header-renderer from the column to the new column-group, so that it appears like there would be new row in the bottom, even though the bottom-most headers are always the same columns.

But this doesn't work because currently it's not possible to change the header after grid is rendered: https://github.com/vaadin/vaadin-grid-flow/issues/155
Otherwise it was working well.

So another approach is use column-groups for all of the header-cells and not set any headers for column elements. This way we can just push the column-groups upwards in the hierarchy without copying headers from a column to a column-group. I have a working POC for this. The only problem is that the bottom-most header-row doesn't have css-border. Probably the web component expects that there's a column-header below any column-group-headers.

**Comment by Legioth** [comment]
If I understood correctly, the original approach works well as long as all configuration is applied during the same round trip that attached the Grid? This probably represents most of the use cases, and might thus be good enough without having to implement a more complex approach.

Once #155 is fixed, the original approach would automatically also work for the remaining cases?

**Comment by pekam** [comment]
@Legioth you are correct. Only appending header rows **after the grid is rendered** doesn't work in the original approach. And it would be automatically fixed with the web component ticket (Or at most it requires us to create new `<template>` elements instead of re-using old ones which is a quick task).

Here's the visual bug if we would use just column-groups: the bottom headers don't have bottom border.
![image](https://user-images.githubusercontent.com/28533233/38916358-c273db2c-42ef-11e8-8af5-293d4fbf37a9.png)

**Comment by pekam** [comment]
@Legioth Your comment convinced me that this would be the better approach.

So to wrap up, the only problem with `HeaderRows` would then be:
Appending rows works only when configuring columns before the grid is attached. You can't append rows after the grid is rendered. The issue causing this is going to be fixed at some point by the components team, so in the future it would work perfectly.

Here you can see the "Basic features" demo code with `HeaderRows`:
https://github.com/vaadin/vaadin-grid-flow/blob/a7473d8820f9538c564e9927288c51025ba03f84/src/test/java/com/vaadin/flow/component/grid/demo/GridView.java#L945

- top-most headers are created with `prependColumn()` and `join()`
- there's an appended `HeaderRow` with a filtering field

@pleku Should we close this spike and create a new ticket?

**Comment by pleku** [comment]
@pekam I'm convinced too. Since there is already three of us (including someone who's name is not Pekka (@Legioth)), I would go ahead and create implementation issue based on this approach.

**Comment by DabhiGhanshyam** [comment]
Hello Pekka Hyvönen,

I have one vaadin-flow grid having the second header row (**_added by using appendHeaderRow() method_**) for searching the content of the grid and **_TextField_** added for each column to that second header row.

Now, I am trying to find/get that TextField and it's value which is searched/entered by user. But I can't able to get that.

Please refers to attached screen-shot.

![gridsearchtextfield](https://user-images.githubusercontent.com/30623161/45938563-b41e4280-bfe8-11e8-8071-2e667c1118c3.png)


I need to find this highlighted TextField and ultimately the searched/entered value '**_2_**'

Please Help

**Comment by pleku** [comment]
@DabhiGhanshyam, for questions on how to do things, please use the forum https://vaadin.com/forum/category/16844704/vaadin-flow thanks.

**Comment by DabhiGhanshyam** [comment]
Hello Pekka Hyvönen,

Thank you for quick response.

I have added question to vaadin forum.

I have asked this here because I find the similar kind of scenario here so. It would great if you could give me some hints or some direction or references to my issue/challenge.

Once again thanks. :)
