### ISSUE TITLE
AbstractColumn::setHeader doesn't work after the grid is rendered

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid-flow#155]
The method changes the content of the header template, but this doesn't update the header cell, and apparently the web component is not supposed to work like that.

Creating a new template element doesn't work either.

I tried copying the content manually:
```javascript
column._headerCell.innerHTML = column._headerTemplate.innerHTML
```
This works otherwise but breaks some CSS in the header cell.

I don't know what should be done for this, but right now we have broken API contract with this method.

**Comment by pekam** [comment]
Issue for the web component:
https://github.com/vaadin/vaadin-grid/issues/1279
If that gets fixed in a way that the header is updated only when creating a new `<template>` element, then we need to change our `setHeader()` to not re-use the old `<template>` element.

**Comment by gilberto-torrezan** [comment]
Replacing the `template` instance on the server-side can be troublesome, since it is used in other parts of the column internals for other stuff (like adding the grid sorter indicator).

One possible solution is to update the state on the server and just notify the client to restamp it (instead of chaging the element instance completely). But that's something that needs to be investigated, I'm not quite sure if it is possible or even the best solution for this problem.

One workaround for this issue is to use a Component on the header (instead of a plain text), and then changing the contents of that Component, instead of changing the template itself.

**Comment by pleku** [comment]
Should be tested with:
- column with just test
- column with sorting indicator
- column with multiple rows
- joined header row cell (eg. two columns joined)

**Comment by pleku** [comment]
This fix could be backported to 1.0

**Comment by mehdi-vaadin** [comment]
There is no `setHeader` in `AbstractColumn`. So I assume this issue is about `setHeaderText`.

**Comment by pekam** [comment]
> There is no `setHeader` in `AbstractColumn`. So I assume this issue is about `setHeaderText`.

There's another protected method `setHeaderComponent`. `Column` still has public `setHeader()` for both text and component.

Anyway, it shouldn't matter if you set text or a component for the header, both methods should end up in the same internal header rendering functionality.

**Comment by pleku** [comment]
In a newer `vaadin-grid` version, there will be a specific API for this - so we can create the tests now and update the component to the new version: https://cdn.vaadin.com/vaadin-grid/5.2.0-alpha5/#/elements/vaadin-grid-column#property-header

**Comment by gilberto-torrezan** [comment]
For the new version, the `<template>` is still needed for when the column is sortable (to add the sorter indicator). Also the `<template>` is unavoidable when using components.
