### ISSUE TITLE
It should be easy to add header and footer rows to Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#157]
As based on feedback for the current API #59 #120 and the `Grid` API in FW 8, it should be easier to add rows to grid's header and footer, and join the cells.

The implementation is based on the spike #147.

### Acceptance Criteria
- The "basic features" demo is changed to match the features presented in the FW8 demo
  - there is filtering text field in one of the header rows
  - thus #120 is resolved
- There is a demo for the simple case presented in #59

**Comment by pekam** [comment]
Actually the footers were not investigated in the spike (my mistake). But I think it's not possible to set multiple footer rows for the web component.

Should there be also `FooterRow` API or is the existing `Column::setFooter` enough?
I would go with the latter since there would be only one `FooterRow` anyway.

**Comment by Legioth** [comment]
> But I think it's not possible to set multiple footer rows for the web component.

Did you try setting adding a  `<template class="footer">` to a `<vaadin-grid-column-group>`? Seems to work for me in https://jsbin.com/yuzimafera/edit?html,output.

**Comment by pekam** [comment]
Damn. :D I tried to try but jsbin was broken for me so I just assumed based on the `<vaadin-grid>` demos that you can set footers only to columns and not column-groups.

Supporting footer rows makes this task a lot more complex, because of joining header/footer cells.

With my current approach, joining two header-cells would join also the footer-cells at the same level, but I think it could work like this:

Joining two header-cells could push another layer of column-groups under the layer where the joining happened. The footer headers on the original layer would be moved to this new lower layer. Then the top layer would have just the header-template and the lower layer would have only the footer-template.

And the same for other way around of course.

**Comment by Legioth** [comment]
Would it make sense to slightly adopt the FW8 API so that there wouldn't be separate `FooterRow` and `HeaderRow` classes, but instead only one class (for which I don't have any good name suggestion), and then you would group columns and set both headers and footers through that same class?

**Comment by pekam** [comment]
I already have this [`ColumnLayer` class](https://github.com/vaadin/vaadin-grid-flow/commit/9a4471c33729fa55b6a7dbc06df1496bb6ce29cb#diff-1dee7aebe9e37b97edab2fc9578468c9) in my WIP-branch. But that is just an implementation detail for representing one hierarchy level of `<vaadin-grid-column>s` or `<vaadin-grid-column-group>s`, as the naming doesn't make any sense if you don't understand how the web component works. I can use that "layer" either `asHeaderRow()` or `asFooterRow()` or both to assign corresponding templates and return either `HeaderRow` or `FooterRow` object for the user.

So I think this `ColumnLayer` is kind of same you are suggesting (with better naming required)? I can't come up with any kind of concept that would make more sense  to Java users than `HeaderRow` and `FooterRow`. And it would probably just be weird for the users if the headers and footers are somehow linked.

The implementation will be maybe complex but I believe it will work out fine. It just requires a lot of organizing those `ColumnLayers`.

For example, if the user has joined some `HeaderCells` and then adds a bunch of `FooterRows` (with not joined cells), there will be a bunch of `ColumnLayers` added below the level with joined headers, and these levels will have only footer-templates (will not effect the headers).

But now if the user wants to join two `FooterCells`, one of which is on the same column as was joined in the header, but the other isn't, we can't support this, because it is impossible with the tree-structure of the column-elements. But I think that these are rare special cases.

**Comment by pleku** [comment]
If it is easier to first a PR just for the headers, go for it. Then the design and implementation can be reviewed earlier. Multiple headers is anyways the more frequent use case. And if it works, we can then do the same for footer or consider it separately.

**Comment by pekam** [comment]
We can't really consider header and footer separately if we want to support both, because they are so tightly coupled in the web component.

I could leave out joining footer cells at first. That makes the task a lot simpler and I would still provide the underlying structure that supports adding that feature later. So there would still be API for adding footer rows, but you could merge only header cells.

**Comment by pekam** [comment]
The feature is implemented in #163 and #181 which also adds the filtering field to the "basic features" demo.

I created a separate ticket for joining footer cells which is still in progress, since the target of this ticket has been already fulfilled. #183
