### ISSUE TITLE
Default HeaderRow

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid-flow#166]
There should be a default header row that is the target for
- `Column::setHeader`
- sorting indicators

After #163 `Column::setHeader` will set the header on the bottom header row (the one that maps to `<vaadin-grid-column>` elements). But this not necessarily what you want when you have appended a header row like in the [Basic Features Demo](https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features).

Sorting indicators also currently go to the header-templates of `<vaadin-grid-column>` elements, so the `<vaadin-grid-sorter>` should instead be directed to the default header row.

My idea was that the default header row would be `null` first, and the first created header row would become the default header row (so you don't need to have any header rows by default, unlike in V8). ~~There would also be getter and setter for the default header row.~~

After this the Basic Features demo can be completed by appending a header row with a filtering field, but having the sorting indicators on the default headers.

**Comment by denis-anisimov** [comment]
I'm pretty sure this ticket is only about default header row.
And I'm not able to do it because there are plenty of issues with header rows functionality which has no sense to fix as a part of this ticket , see #170.
So technically header rows functionality is completely broken at the moment and should be fixed before this ticket. 
This ticket blocked by #170 (or may be bunch of tickets splitted from the #170).

**Comment by mvysny** [comment]
Thank you, I agree with the need of having the default header. Currently the sorting indicators are always attached to the bottommost header, and if that happens to be the filter bar, the result is quite amusing :)
![screenshot from 2018-05-03 18-39-21](https://user-images.githubusercontent.com/254091/39587353-fad53b00-4f01-11e8-99a7-e782e1a48d9a.png)
You can see the full app here: https://vaadin-kotlin-pwa.herokuapp.com/
