### ISSUE TITLE
Appending multiple HeaderRows with components bug

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid-flow#172]
When you append more than one HeaderRow during the same server roundtrip and use components in the HeaderCells instead of text, the contents of the first appended row remain on the bottom row, as can be seen in this example: https://github.com/vaadin/vaadin-grid-flow/issues/170

The `appendHeaderRow()` implementation moves renderers from `<vaadin-grid-column>`s to `<vaadin-grid-column-group>`s but apparently overriding the rendering still makes the original rendering happen. This is most likely caused by the `ComponentRenderer` registering a `beforeClientResponse` command which sets the template.

**Comment by denis-anisimov** [comment]
This issue pretends to supersede the issue #170.
I'm not sure about it.
Please make sure that there is no issue in this comment (when this issue is fixed):
https://github.com/vaadin/vaadin-grid-flow/issues/170#issuecomment-384715307

If this issue doesn't fix anyhow mentioned comment then #170 must be reopened and fixed separately.
