### ISSUE TITLE
Automatically added columns should be sortable if values are comparable

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-grid-flow#206]
When using  in "bean grid" style, I'd expect all comparable columns to be sortable by default, especially if assigning data directly with setItems method (= skipping all DataProvider stuff and using plain collections API).

This is also how Vaadin 8 version of Grid works.

**Comment by pleku** [comment]
Since this is just forgotten to do, and has worked previously in a different way, we're considering this as a regression in V10 / 1.0 instead of a new feature.

When this is backported to V10, there needs to be a specific mention in the release notes that this fix changes the default behavior a bit (but was due to a regression).

**Comment by mstahv** [comment]
Was something done to this issue or why was it closed?

**Comment by mstahv** [comment]
I guess this was the commit that was used to close the issue: https://github.com/vaadin/vaadin-grid-flow/pull/286/commits/eaeb93daf63c62d43385a75470d606fe8a5b1383
