### ISSUE TITLE
Vaadin-grid not populated

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid-flow#316]
_From @KrifaYounes on August 17, 2018 9:1_

My vaadin-grid is not populated when I used it like this : 
Someone have an idea why my grid is not populated ? It's only popupaled when I access to the page with reload but not with routing.

```
@Tag.... @HtmlImport.....@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class Booking extends PolymerTemplate<BookingModel> {
   @Id("groupsList")
   private Div groupsList;

   public Booking () {
        FlightBookingView  flightBooking = new FlightBookingView  (....);
        groupsList.add(flightBooking )
   }
}

@Tag... @HtmlImport....@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class FlightBookingView  extends PolymerTemplate<BookingModel> {

    private @Id("headerComponent") HeaderComponent headerComponent;

    public FlightBookingView  (BookingGroup bookingGroup) {
       headerComponent.load(bookingGroup);
    }
}


@Tag.....@HtmlImport....@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class HeaderComponent extends PolymerTemplate<BookingModel> {

    private @Id("estimateItemDiv") Div estimateItemDiv;
    public HeaderComponent (){}

    public void load(BookingGroup bookingGroup) {
        EstimateItemGrid estimateItemGrid = new EstimateItemGrid();

        List<EstimateItemDto> estimateItemDtos = ..//multiple elements in list
        Stream<EstimateItemDto> estimateItemDtoStream = new ArrayList<EstimateItemDto>().stream();
        estimateItemGrid.setColumns(estimateItemDtoStream);
        ListDataProvider<EstimateItemDto> dataProvider = new ListDataProvider<>(estimateItemDtos);
        estimateItemGrid.setDataProvider(dataProvider);
        estimateItemDiv.add(estimateItemGrid);
    }
}
```

_Copied from original issue: vaadin/vaadin-grid#1370_

**Comment by Legioth** [comment]
Hi. I cannot see any obvious reason for why it wouldn't work only based on the example code included in this ticket. Furthermore, I cannot test the code myself since there's various parts omitted from the code.

One thing that looks suspicious is the way `setColumns` is called with an empty `Stream`. The `setColumns` method in `Grid` only accepts `String... propertyNames` as the parameter, so I would assume `EsitmateItemGrid` has a custom implementation for that case? Could it be that there aren't any columns configured for the Grid and it therefore looks like it's empty?

Another thing that you could look out for is that in some layouting situations, the height of the Grid component will end up as 0px which in turn makes it seem like it's empty. You could verify whether this is the case by setting an explicit height for the Grid either through Java or in the template.

**Comment by KrifaYounes** [comment]
@Legioth but it's not working when I navigate beetween tab it's only work when I access to the page direclty

**Comment by Legioth** [comment]
In that case, I have no further guesses on what might cause the problem without having example code that I could try run on my own machine to be able to pinpoint exactly what differs between the successful and problematic cases.

**Comment by KrifaYounes** [comment]
Hi @Legioth 
I created a project that contains my issues 
the repo is available here : https://gitlab.com/outrun13/vaadin-grid-sample

my vaadin-grid is not populated when I click on the second tab but the grid is populated when I try to access to the second the second time.
Thanks for help;

**Comment by KrifaYounes** [comment]
Hi @Legioth 
Have you had the time to look my project with the vaadin-grid issue ?
It's blocking for us, we have a vaadin pro account.
email : younes.krifa@perfectstay.com
companyname : perfectstay

thanks,

**Comment by Legioth** [comment]
I simplified your example code and reported it as a core Flow issue in https://github.com/vaadin/flow/issues/4557.

The problem here is a combination between nested levels of `@Id` and `setVisible(false)`. The best workaround in your code would most likely be to attach and detach the tab contents instead of using `setVisible` to toggle them.

**Comment by KrifaYounes** [comment]
Hi @Legioth 
how to attach and detach the tab contents instead of using setvisible ?
thanks a lot

**Comment by Legioth** [comment]
In your example, you could remove `selectedPage.setVisible(true);` and instead make it remove the previous content from `pages` and instead add `selectedPage`, e.g. something like 
```
pages.removeAll();
pages.add(selectedPage);
```
You'd then also need to remove the places where `setVisible(false)` is called.
