### ISSUE TITLE
SPIKE: Investigate making the inline editor available for Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#324]
Investigate how we can make it possible in terms of API and web component integrations for having similar featureset as with FW 8 Grid:
- Binder integration
- Callback on server side for the row editor generation
- Good keyboard navigation support as with the web component
  - tabbing goes between the fields and rows
  - there is a default key specified for starting editing or concluding it, should be modifiable
- Enabling the editor should be possible
  - via default UI buttons that are modifiable 
  - via default keyboard shortcut that is modifiable
  - possibility to customize, an example with using just buttons with icons
- Buffered and nonbuffered mode
  - There is Save / Cancel buttons for buffered mode
    - need a default location for those 
    - need a way for setting the labels for the save / cancel

**Comment by pleku** [comment]
Related to #135

**Comment by pekam** [comment]
Here's my POC of how this can be implemented: https://github.com/vaadin/vaadin-grid-flow/commit/387302aa267d6a625183545f6c441e543c6883fa
In this example
- `Column::setEditorComponent` defines the component which is rendered instead of the regular content when the row is edited
- `Grid::editItem` renders editor components instead of the regular content for the given item
- You can define one column for the edit buttons quite easily with a component renderer, like `grid.addComponentColumn(item -> new Button("edit", e -> grid.editItem(item)));`. Then you can set for example save and cancel buttons as the editor components for this column, so they will be shown instead of the edit-button when the row is edited. We can of course add helpers / default implementations for this kind of column, but this allows already a lot of customization, since you have full control of how the column is rendered.
- One problem for the default implementation with buttons is that we would need to make grid depend on button, or use `NativeButton`. IMO creating a column with the editor buttons is so simple that we don't need to consider any default implementation at least in the first implementation. Just provide a good demo example.
- The Binder is used in the demo-page for binding the values to the editor components. In the real implementation it should belong to the grid.

![image](https://user-images.githubusercontent.com/28533233/45474415-6715b300-b742-11e8-9749-819b5fc0a5a0.png)

So the technical problems related to teleporting editor component to the currently edited row are solved. This makes it already possible to implement quite useful editor row feature.

Buffered/unbuffered mode is not shown in the code, but it should be as simple of using either `Binder::readBean` and `Binder::writeBean`, or `Binder::setBean`, which saves changes immediately.

I will continue investigating how to improve the convenience with keyboard navigation etc.

**Comment by pekam** [comment]
Defining a key which opens the editor: https://github.com/vaadin/vaadin-grid-flow/commit/682e5671e44a0a17ef100b3f9c7cae7fcaa1cd00

Focusing automatically on the first field when opening the editor: https://github.com/vaadin/vaadin-grid-flow/commit/42b43c834de8cb746db63e917c821df3a27dfb30

**Comment by pekam** [comment]
Saving changes and closing editor on keypress: https://github.com/vaadin/vaadin-grid-flow/commit/6d58f08a4ceb29f39fe257832d8c72856a5ebda7

> Callback on server side for the row editor generation

The editor is always opened through the server-side `Grid::editItem` method so callback can be called in that point.

I think that is all. The full POC can be found in the `spike-editor` branch. https://github.com/vaadin/vaadin-grid-flow/tree/spike-editor

**Comment by pwilkin** [comment]
An implementation with `setEditorComponent` sufffers from the same problems the old Vaadin 8 version did - it does not allow to use dynamic editors, i.e. different editors for different rows. A common case is that a `ComboBox` is populated with different items depending on the data in the row (country -> city case). 

It would be nice if an alternative (say `setEditorComponentProvider`) could be provided instead. Also, there should be some sort of hook for `isRowEditable`.

**Comment by pekam** [comment]
Thanks for the feedback!
Could you elaborate on your use-case though? I don't really understand why you would use a different component for the same property of a same bean type.

Anyway, I think it should be possible by defining a container component as the editor component, and changing its content on the event which should be fired when the editor is opened.

**Comment by pekam** [comment]
And btw, the `setEditorComponent` is not decided as the API. It's just something I made quickly for my POC, because I didn't want to add the whole `Editor` API.

**Comment by pwilkin** [comment]
A real-life use case that we face: we have a related object selector field that, depending on the row at hand, is either restricted or unrestricted. If it's restricted, we want to render it using a combo box. If it's unrestricted, we want to render it using a custom selector of ours (a filtering field that opens a selection list). 

Using a container is not really viable since it violates the binder linking. We already do that in v8 and it's a mess - we have to constantly manage / switch the binding ourselves. 

What would be nice is an interceptable event that would actually allow you to change the bindings / components before the editor is actually opened. In v8, the event is called when the components are already in place.

**Comment by pekam** [comment]
Ok, now I get it. This should be indeed taken into account, and I don't see a reason why we couldn't make a server-roundtrip before changing to editor-content, to allow this interceptable event to be handled.
