### ISSUE TITLE
API to reorder columns

### ISSUE THREAD

**Issue by oluwasayo** [vaadin/vaadin-grid-flow#333]

**Comment by Legioth** [comment]
There is already `setColumns(String... propertyNames)`, but it only works if you are using the bean grid functionality.

**Comment by oluwasayo** [comment]
That means the application developer would have to discover all the columns on their own.
 
Some use cases:

1. You have a `Crud<Anything>` custom component which delegates column generation to Grid but you want to identify some columns if present and move them to a specific position. Something like:
```java
grid.getColumns()
    .stream()
    .filter(e -> e.getKey().equals("id"))
    .findFirst()
    .ifPresent(e -> grid.moveColumnToIndex(0));
```

2. You want to move columns around based on events in the application e.g in the settings tab of an application, the user selects a checkbox like "Last name first".

These examples might seem quite specific but with #334 and #335 it's hard to achieve these objectives even with a Grid subclass. If it's impossible to reorder, one should at least be able to remove a column and re-insert it into a specific index.

**Comment by heruan** [comment]
One other use case would be having `setColumnResorderingAllowed(true)` to let the user reorder the columns and then save the preferred order to user preferences, to be restored when the user returns.

**Comment by petrixh** [comment]
This issue affects a migration from v8 to v14 for a customer as well. Any ETA on when this and the API to listen to column reorder through DnD could be added to the Platform?

**Comment by tomivirkki** [comment]
As a workaround, you can programmatically invoke the same (private though) APIs that manual column reordering uses with:

```java
List<Column<Component>> columns = grid.getColumns();

Button button = new Button("Switch", e -> {
  grid.getElement().executeJs("this._swapColumnOrders($0, $1)",
    columns.get(0).getElement(), columns.get(1).getElement());
});
```

**Comment by steffen-harbich-itc** [comment]
Wouldn't it be easy to add a methods like `addColumn(int index, ...)` to `Grid`? That way we could use `removeColumn` and `addColumn` to reorder programmatically.

**Comment by jcgueriaud1** [comment]
I started to implement an API to reorder columns.
Here the diff:
https://github.com/vaadin/vaadin-grid-flow/compare/master...jcgueriaud1:column-reorder-listener

Add JAVA API for column reordering #333 
- Add a listener
- Retrieve the columns in the right order
- Update the column order from Java

I tried to use the same API as in Vaadin 8.

WIP or to change:
- Synchronise _order property: Shouldn't be used in the JAVA Side as it's private (should be changed in vaadin-grid? )
- setColumnOrder is working when it's called when the grid is added but I had to change vaadin-grid. (by default vaadin-grid always reset the order when a column is created)
- API limitations: Cannot reorder columns in different groups from JAVA, cannot reorder column group.
- Tests are quite simple and there is no automatic test when a column is reordered from the client side (with drag&drop)

If you think some JAVA methods should be added, feel free to comment.

Other tickets related to this one:
 #338 - should be ok
 #334 - No JAVA API for that but perhaps it's not really hard to do. At least it's possible to add a column at the end and set the order.

**Comment by tomivirkki** [comment]
Looks good. Ideally the private `_order` properties shouldn't be used from Java as you mentioned. Nor should `vaadin-grid` expose them as the values reflect the implementation details (they can be something like 31000000). If the properties were public, users would need to be careful and aware of the implementation in order not to set invalid values.

Would it help if the `vaadin-grid` instead exposed some means to set the column orders by the column references? Something like https://github.com/vaadin/vaadin-grid/commit/4d4b06c757d077e2e551a254e5f40e015e63d043#diff-345b086c36f15531896359294c586da4R306

**Comment by tomivirkki** [comment]
Or maybe the Java API could just reorder the `<vaadin-grid-column>` elements (under the `<vaadin-grid>`). That would also make the new order permanent so it wouldn't be reset when new columns are added.

**Comment by jcgueriaud1** [comment]
I used _order attribute for:
* retrieve the column's order
* update the column order -> setColumnOrders may do the job and it does check if you can swap columns or not. But how can I retrieve the error from Java? 

I can hide Column.set/getOrder from the public API. I don't know if it's required.

The other problem that I can't reorder the column group because in Java there is no public API to retrieve the column groups.

**Comment by tomivirkki** [comment]
> I can hide Column.set/getOrder from the public API. I don't know if it's required.

That might be better as the `_order` as I mentioned, is an implementation detail rether a meaningful order number.

> The other problem that I can't reorder the column group because in Java there is no public API to retrieve the column groups.

If the API ordered the column DOM elements instead, you have access to column groups also:

![Screenshot 2019-08-12 10 42 31](https://user-images.githubusercontent.com/1222264/62851175-f67a6c00-bced-11e9-9d64-ab5e98a97fee.png)

**Comment by jcgueriaud1** [comment]
I make a commit with 2 solutions: https://github.com/vaadin/vaadin-grid-flow/compare/master...jcgueriaud1:column-reorder-listener
Changes from the last commit:
* make setOrder / getOrder protected, it's not in the public API
* Fix the 1st solution. Try to use _order and swap order of the columns if _order = 0 then put the column at the end (append the column).
* Add a second solution: There are still a lot of problems with this solution (but it does not use _order property). See comment on Grid.setColumnOrder method

**Comment by mvysny** [comment]
@steffen-harbich-itc the `Grid.addColumn()` is already overloaded too many (11 methods :( ). Also `removeColumn()` is quite destructive - it throws away the element and the component along with its state, so you need to manually replicate the column configuration when creating a replacement one. An API that moves columns around (e.g. `moveToIndex()` or `setColumnOrder()`) is much easier to use since the columns do not need to be manually re-created.

@tomivirkki @jcgueriaud1 I think the DOM reshuffling is a safer choice here, since the ordering will be remembered even in case of `@PreserveOnRefresh` when the user hits `F5`. It's trickier to implement though, especially when there are multiple headers (or the header cells are joined). Yet it can be done.

@jcgueriaud1 thank you so much for your amazing work with the PR! However, since it contains two separate pieces of functionality (1. setting the order of the columns, 2. column-reorder listener) I'll need to break the PR into two. I've already created a PR for column-reorder listener here: https://github.com/vaadin/vaadin-grid-flow/pull/756 .

**Comment by mvysny** [comment]
I've created an initial PR #757 which fixes this issue. The current limitation is that reordering columns in a Grid with joined header/footer cells is not currently supported. That is partly because of https://github.com/vaadin/vaadin-grid/issues/1646 and partly because of potential complexity of such algorithm.
