### ISSUE TITLE
Spike: scrollTo methods for Grid & TreeGrid

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#336]
Related to #327 figure out the proper way to bring support to methods `scrollToBeginning`, `scrollToEnd` and preferably also `scrollToIndex`. For `TreeGrid` the `scrollToIndex` should probably be related to the current data set as a flat set (every row is just considered as one row regardless of level).

**Comment by denis-anisimov** [comment]
There is already ticket in Grid for a public `scrollToIndex` method.

https://github.com/vaadin/vaadin-grid/issues/1169

Meanwhile we can use existing `_scrollToIndex`  method.
I confirmed with components/elements team that it should work.

One note about how it works:
-it works for `Grid` without any surprises.
- for tree grid the index is _the index of the currently visible items_. So the index is not the index of the flattened data but it's the row index in the grid which represents currently expanded tree grid.

So if you have the hierarchical **_data_** structure like that:
- one
    |
    - subone
- two

Then `_scrollToIndex`  depends on the current tree grid state: if everything is collapsed then
`_scrollToIndex(1)` means scrolling to the item `two`.
If everything is expanded then `_scrollToIndex(1)` means scrolling to the item `subone`.

So if we want a different behavior on the server side then we need take into account of the current behavior the method on the client side (so we will need to recalculate index based on expanded nodes).

Regarding to the  #327:
the reason of this behavior is asynchronous nature of data update.
So it's totally fine to call `_scrollToIndex` as a JS function in the way described in the ticket.
But data provider update calls chain should be taken into account.

Here is the code snippet from the action which updates the tree grid data:

```
String newItem = String.valueOf(lastAdded.getAndIncrement());
            treeData.addRootItems(newItem);
            treeGrid.getDataProvider().refreshAll();
            treeGrid.getSelectionModel().select(newItem);
            treeGrid.expandRecursively(Collections.singletonList("0"), 1000);
            treeGrid.getElement().callFunction("_scrollToIndex", lastAdded.get());
```

Here is what happens when similar code is called on plain Grid or TreeGrid with no hierarchical data:
- 1 update HTTP response from the server side to the client side as a result of `click` action.
- the `setRequestedRange` is requested to be called once from the client side to the server side.

Here is what happens with hierarchical data:
- 1 click handler HTTP response (the same)
- then **a number** of client side <-> server side communications with the `setRequestedRange` method calls from the client side and response from the server side with data (which apparently populates the hierarchical data). I see 19 such communications.

As a result:
- `_scrollToIndex` is called on the client side as it should. But it's done in the very first response to the client side.
- after that there were a number of RPC calls which has modified the data and reset the scroll index

What does it mean for us:
- we may not call  `_scrollToIndex` if data provider update operation is in progress. It has to be postponed somehow in `scrollToIndex`  Java API.
- perhaps we should expose somehow a method which allows to defer _any_ operation whose result is meaningful after data provider update is finished.
- it might be that there are other _already existing_ methods which also should be deferred. We need some review for existing methods and defer their execution after data update is completed (if there is an active update).
