### ISSUE TITLE
Spike: Grid Editor with callback(s) for dynamically generating the editor

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#358]
As based on feedback from #324, there should be a way to specify the editors for a certain grid column on the fly based on the bean instance - meaning it that there might be different editor components used for the same column on different rows. 

The roundtrip is not an issue since the editor contents are always created in a roundtrip.

The API could be eg. `setEditorComponent(item -> item.isCountry() ? getCountryEditor() : getCityEditor())`, but since there is also a possibility to set the binding for the column, we should consider would it be also feasible to customize the binding dynamically for each row.

The purpose of this spike is to research an API proposal for the use case of creating a customized editor component / binding for different rows.

**Comment by pleku** [comment]
To successfully conclude this spike, you will have to show the usage of the API in a demo where some of the columns are editable and some are not based on the row/item.

**Comment by gilberto-torrezan** [comment]
Created a spike on the branch https://github.com/vaadin/vaadin-grid-flow/tree/gilberto/358_editor_callback

The implementation is based on a new `DataGenerator`: the `EditorDataGenerator`. This generator is responsible for managing the editor components and editor bindings for a given column.

It follows the same principle as the `ComponentDataGenerator`: it creates whatever needs to be created at `refreshData` time, and send the correct data to the `<flow-component-renderer>` on the `generateData` method. In that way, the Column itself doesn't have to have any logic related to how the data is transmitted.

Also, since the generators are always invoked in the `beforeClientResponse` loop, no extra logic is needed on the column side in order to the callbacks to work.

The open questions are:

* Should be state of the editor components change while the bean is being updated in not-buffered mode?

Currently the demo at the `GridView` class is using this code in order to the components to be able to be replaced while the bean is being updated:

```
binder.addValueChangeListener(event -> {
    grid.getDataProvider().refreshItem(binder.getBean());
});
```

... but looks like it should be managed by the component itself, not by the developer.

* When to cleanup the bindings and components?

Using the `destroyData` method to clean up the state of the DataGenerator is not possible, since it creates an invalid state when the user scrolls away from the item, and scrolls back. I have the feeling that nothing should be cleared at all (as it wasn't cleared in the previous implementation anyway), but that needs a better investigation.

* Should it allow null editors?

Since now it's possible to return an editor based on the state of the item, it's worth questioning whether `null` (or "no") editors should be supported as return of the editor callback. The spike allows it, but the implementation is buggy. Some tests need to be added.

* What the `getEditorComponent` and `getEditorBinding` should return when a callback is set instead?

In the spike, those methods return `null` when the callbacks are used, but they could return the last component/binding used instead.

--
This spike doesn't contain proper javadocs or an extensive demo (or unit/integration tests), so it could be used as the base of a final design, but not as-is.
