### ISSUE TITLE
Issue with dynamic height and data provider

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-grid-flow#383]
I have a grid with `height-by-rows` set via `grid.setHeightByRows(true)` and a data provider. When the page load, the data provider is immediately queried with:

- offset: 0
- limit: 50

then

- offset: 50
- limit: 100

then

- offset: 150
- limit: 4500

at which point it hangs.

All the three queries happen without any interaction (i.e. no scrolling) after page load.

**Comment by heruan** [comment]
Sample project replicating the issue: https://github.com/heruan/vaadin-spring-demo

Run with `mvn spring-boot:run` then go to http://localhost:8080/grid-dynamic-height

The console will log:

```
Offset: 0, Limit: 50
Offset: 0, Limit: 50
Offset: 50, Limit: 100
Offset: 150, Limit: 250
Offset: 400, Limit: 200
Offset: 600, Limit: 750
Offset: 1350, Limit: 650
Offset: 2000, Limit: 1000
Offset: 3000, Limit: 3650
```

and pretty soon the UI will hang.

**Comment by Legioth** [comment]
I still think this scenario should be fixed so that all items are fetched at once instead of doing lots of round trips.

**Comment by gilberto-torrezan** [comment]
@heruan what do you consider to be the issue when you opened the ticket: the fact that the DataProvider is queried for all the items, or the fact that all the items are fetched in several consecutive queries (instead of a single one) ?

**Comment by heruan** [comment]
@gilberto-torrezan Why all the items are fetched if I set `height-by-row`? Isn't that quite limiting when using a data provider? With `IronList` this doesn't happen, i.e. the list loads only the visible items, regardless of its height. I'd expect the same for `Grid`, when I can't set a fixed height or I want the grid to scroll with the document.

So I consider an issue that lazy loading doesn't work with dynamic height 🙂

**Comment by Legioth** [comment]
The core issue here is that `<vaadin-grid>` lacks functionality to take outer scrolling contexts into consideration. It instead only looks at what would be needed based on the height and position of its own scrollbar, which in a `height-by-row` case means that all items should be fetched and rendered.

Considering outer scroll positions and heights when fetching items is implied by https://github.com/vaadin/vaadin-grid/issues/1364 but not directly written out there. Once that kind of functionality is added to the web component, the Flow integration would also automatically work as expected.

Another problem in this case is that the lack of this functionality leads to quite weird behaviour when the Grid continuously discovers that more items would be needed as it keeps rendering more items. Fetching everything at once would still not be what a developer would expect, but it would make it clear what goes on compared to the current situation where the items are fetched in small batches.

I was originally thinking that the Flow integration could deal with this situation by eagerly fetching all items from the data provider and populating the client-side cache. I did however realize that the fix should actually be in the web component instead so that it would eagerly fetch all items from its own data provider instead. In that way, there would also not be any "workaround" on the Flow side that would have to be removed later on when/if `setHeightByRows(true)` would be updated to take outer scrolling into account.

In either case, there isn't really anything to fix in the Flow integration. It should all go into the web component. I've added a clarifying comment to https://github.com/vaadin/vaadin-grid/issues/1364 and opened https://github.com/vaadin/vaadin-grid/issues/1475 about making the web component request all rows at once.
