### ISSUE TITLE
The inline editor doesn't allow focusing editors

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#404]
In the `GridView::createBufferedEditor` demo, if you modify the edit button listener:
```java
        Column<Person> editorColumn = grid.addComponentColumn(person -> {
            Button edit = new Button("Edit");
            edit.addClassName("edit");
            edit.addClickListener(e -> editor.editItem(person));
            field.focus();
            return edit;
        });
```
By adding `field.focus()` you get client side exception.

It is mandatory to be able to focus any of the fields when the editor is opened.

**Comment by pleku** [comment]
Just for clarity: all the editor demos should always focus the first input field when opened, not just the one mentioned in the issue description

**Comment by gilberto-torrezan** [comment]
Marking the field as `field.setAutofocus(true)` makes the focus work for the field when the editor opens - but only for the first time. When a second editor is opened with the same field, the focus is never regained.

**Comment by gilberto-torrezan** [comment]
The client-side exception is caused by https://github.com/vaadin/vaadin-text-field/issues/269

But even when the bug gets fixed, it won't make the `focus()` method on Flow work.

The editor component is attached to the DOM by the template engine on the browser. It is stamped from a `<template>` with a `<flow-component-renderer>`. In other words, the server-side Flow doesn't know when the component gets attached in order to call the `focus()` function at the right time.

One workaround for that is to include a timeout, like this:

```
grid.getEditor().addOpenListener(event -> UI.getCurrent().getPage()
                .executeJavaScript("setTimeout(function(){$0.focus();}, 0);",
                        field.getElement()));
```

It works but it is definitely not developer-friendly.

To properly fix this, there should be a way to either:

- Hide the timeout function from the developers, so they can just call the `focus()` without problem. This could be done on the wrapper class, the client-engine or the webcomponent;
- Create a mechanism on Flow that allows the `flow-component-renderer` to notify the server-side when a component is attached to the DOM.
