### ISSUE TITLE
V12 TreeGrid expandRecursively is very slow compared to V8 [3d]

### ISSUE THREAD

**Issue by szymonjagiello86** [vaadin/vaadin-grid-flow#476]
https://vaadin.com/forum/thread/17460101/17460830
Hi, 
we were using Vaadin 8 (8.6.3) TreeGrid but moved to Vaadin 12 (12.0.3) lately. Expanding all elements with V8 worked really nice but not with V12. Is there an efficent way to exapnd all elements recursively? Will this be fixed in the future? I attach example projects:

[vaadin8.zip](https://github.com/vaadin/vaadin-grid-flow/files/2749318/vaadin8.zip)
[vaadin12.zip](https://github.com/vaadin/vaadin-grid-flow/files/2749319/vaadin12.zip)

Br, 
Szymon Jagiełło
Maja Staniszewska

**Comment by TomRauchenwald** [comment]
We're facing the same issue, we'd like the default state of our TreeGrid to be expanded, but expanding the nodes takes too long.

**Comment by sigsegv4** [comment]
Same issue here, expanding the grid takes to long if a fully expanded grid is needed. Is there any plan for the future?

**Comment by robert-lee-hisl** [comment]
Also looking to show a tree with all rows expanded initially. Expanding all elements is painfully slow with many root items.

**Comment by sascha-broich** [comment]
It's Vaadin 14.1 and still an issue.
Expanding seems to happen as an animation even if the items are initially set as expanded.

**Comment by guttormvik** [comment]
Just encountered this issue in 14.1.
I'd like to add that the expansion is incorrect as well.
If I paste filter-value into my ValueChangeMode.EAGER filter-field, the filtering is correct, but if I type it letter by letter the finished filtered list is 4x as long as it should be (because my filter had 4 letters?) and it is garbled; repeating sections; empty lines.
If I switch to ValueChangeMode.LAZY it seems to behave.

**Comment by tulioag** [comment]
@guttormvik It seems like a different issue. Could you open a new issue about that?

**Comment by pekam** [comment]
I'm reopening the issue and moving it back to our backlog.

The issue was earlier resolved by optimizing the client-side rendering/scripting logic.

The real issue, however, is that TreeGrid requests one level of items at a time from the server, causing a request-render loop with multiple roundtrips through the network.

To resolve the issue, TreeGrid should send enough items to fill the viewport already in the initial response. The child items should be visible already after the first render.

Since the server can't know the grid's viewport size in advance, the "normal" Grid seems to simply send `pageSize` items in the initial response. TreeGrid could find the first `pageSize` items with depth first search, taking into account the expanded nodes, and send those to client in the initial response.

**Comment by tomivirkki** [comment]
What @pekam described above is essentially the same as https://github.com/vaadin/vaadin-grid-flow/issues/802 TreeGrid performance was significantly improved by https://github.com/vaadin/vaadin-grid-flow/pull/1084
