### ISSUE TITLE
TreeGrid in multi-select mode throws IllegalArgumentException

### ISSUE THREAD

**Issue by tltv** [vaadin/vaadin-grid-flow#506]
Enabling TreeGrid multi-selection with `setSelectionMode(SelectionMode.MULTI)` makes selections from client side throw `java.lang.IllegalArgumentException: Hierarchical data provider doesn't support non-hierarchical queries`.

Its thrown from `HierarchicalDataProvider.size(Query<T, F> query)` which is called from `AbstractGridMultiSelectionModel.selectFromClient(T item)`.

There it makes a call like this: `getDataProvider().size(new Query<>())` which is not correct with TreeGrid. It should count whole hierarchy similar way done in `AbstractGridMultiSelectionModel.clientSelectAll`.

Tested with platform 12.0.3/12.0.5. Related methods looks untouched in master branch too.

**Comment by mstahv** [comment]
A code snippet to reproduce:

```
public class MainView extends VerticalLayout {
    
    public static class Person {
        
        private String name;
        private int yearOfBirth;
        private Person supervisor;
        private Collection<Person> slaves = new ArrayList<>();
        
        public Person(String name, int yearOfBirth) {
            this.name = name;
            this.yearOfBirth = yearOfBirth;
        }
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        public int getYearOfBirth() {
            return yearOfBirth;
        }
        
        public void setYearOfBirth(int yearOfBirth) {
            this.yearOfBirth = yearOfBirth;
        }

        public Person getSupervisor() {
            return supervisor;
        }

        public void setSupervisor(Person supervisor) {
            this.supervisor = supervisor;
        }

        public Collection<Person> getSlaves() {
            return slaves;
        }
        
        @Override
        public String toString() {
            return "Person{" + "name=" + name + ", yearOfBirth=" + yearOfBirth + '}';
        }
        
    }
    
    public MainView() {
        
        Person boss = new Person("Boss", 0);
        Person jorma = new Person("Jorma", 0);
        Person kalle = new Person("Kalle", 0);

        jorma.setSupervisor(boss);
        kalle.setSupervisor(kalle);
        boss.getSlaves().add(kalle); boss.getSlaves().add(jorma);
        
        TreeGrid<Person> grid = new TreeGrid<>(Person.class);
        grid.setItems(Arrays.asList(boss), b -> b.getSlaves());
        grid.setHierarchyColumn("name");
        
        grid.setSelectionMode(Grid.SelectionMode.MULTI);
        
        add(grid);
        
    }
    
}
```

**Comment by hordurth** [comment]
This is a problem in 13beta1 also.

**Comment by Klaudeta** [comment]
The fix seems straightforward, anyway I think the AbstractGridMultiSelectionModel.clientSelectAll itself has a flaw regarding lazy loading of children.
AbstractGridMultiSelectionModel.clientSelectAll is recursively loading the whole hierarchy, this way breaking the lazy loading feature (IMO)  of the DataProvider. So child items that are not rendered on client side (their parent might be not expanded) are being loaded just to satisfy the clientSelectAll method.

**Comment by Klaudeta** [comment]
Wouldn't somehow make sense AbstractGridMultiSelectionModel.clientSelectAll to select only already rendered items on the grid and then for any item being expanded add its rendered children to the selection?

**Comment by Legioth** [comment]
As discussed separately, the challenge is that users in general expect that the select all checkbox sill select all items, regardless of whether they're currently visible or not.

The only generic way of implementing that requirement is to eagerly load all items from the data provider, regardless of any lazy loading.

Similar end-user results can be approximated with a special "all selected" mode where items that are unselected are tracked instead of items that are selected. The problem with this approach (in addition to the increased internal complexity) is that any items that have been added to a backing database after the user chose to select all items will also be considered as selected.

**Comment by Klaudeta** [comment]
> As discussed separately, the challenge is that users in general expect that the select all checkbox sill select all items, regardless of whether they're currently visible or not.

Exactly, that's why I think that there is no need to distinguish between items being added to a backend database before and after the select all check if they are both not visible to the user the moment he checks select all.

> The problem with this approach (in addition to the increased internal complexity) is that any items that have been added to a backing database after the user chose to select all items will also be considered as selected.

To reenforce that this is too ambiguous to the user lets consider this:

1. the tree grid having all items collapsed
2. user checks the select all checkbox
3. user expands one of the root items and finds out 5 children, the first 3 selected and the last 2 not selected. 

How can we set a rule so each end user understands that the only reason why 2 children are not selected is because they were added just half a second after he clicked the select all checkbox? 

The select all feature should be completely clear and it could be if we just choose one of the options for it behavior:

1.  If select all checkbox is checked, each item becoming visible to the user should be selected, no matter when it has been added to the DB (user becomes aware of it when the item is visible on the grid not when it has been added to the backend DB)
2. If select all checkbox is checked, only items being visible to the user at that moment will be selected and nothing else.

And of course we could have this two options configurable after deciding which is best to be the default one.

In both cases the performance issue and braking the lazy loading feature of the data provider are automatically resolved.(no need anymore to load all the items (visible and not)) when select all is checked.

**Comment by ugurdoksan** [comment]
I think the bug is not solved. I am using v13.0.0 but it throws the same exception

**Comment by tlimbach** [comment]
Is there any solution or workaround present?

**Comment by Klaudeta** [comment]
The fix will be available with the next release of vaadin-grid-flow 3.0.X as it is already in the master branch.
Meanwhile a workaround would be to suppress the exception:

```
/**
 * This is a custom implementation for {@link AbstractGridMultiSelectionModel} to be used solely
 * with a TreeGrid when in multi select mode to workaround the issue:
 * https://github.com/vaadin/vaadin-grid-flow/issues/506
 * until it's fix will be released.
 *
 * @param <T>
 */
public class CustomGridMultiSelectionModel<T> extends AbstractGridMultiSelectionModel<T> {

    public CustomGridMultiSelectionModel(Grid<T> grid) {
        super(grid);
    }

    @Override
    protected void fireSelectionEvent(SelectionEvent<Grid<T>, T> selectionEvent) {
        ComponentUtil.fireEvent(getGrid(), (ComponentEvent)selectionEvent);
    }

    public void selectFromClient(T item) {
        try {
            super.selectFromClient(item);
        }catch (IllegalArgumentException e){
            /**
             * Suppressing this IllegalArgumentException exception because:
             *
             * The super implementation of this method throws an IllegalArgumentException exception
             * when multi selection is used in TreeGrid. For more details:
             * https://github.com/vaadin/vaadin-grid-flow/issues/506
             *
             * This {@link CustomGridMultiSelectionModel} class should be removed once the fix for the issue has been released.
             */
        }
    }

}
```
```
public class InternalTreeGrid<T> extends TreeGrid<T> {

    @Override
    public GridSelectionModel<T> setSelectionMode(SelectionMode selectionMode) {

        if(selectionMode == SelectionMode.MULTI){
            GridSelectionModel<T> selectionModel = new CustomGridMultiSelectionModel<>(this);
            super.setSelectionModel(selectionModel, selectionMode);
            return selectionModel;
        }else{
            return super.setSelectionMode(selectionMode);
        }


    }
}
```

**Comment by tlimbach** [comment]
Thanks for your realy fast help! Now it's working! 👍
