### ISSUE TITLE
TreeGrid hierarchy breaks after consecutive data provider refreshes

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/vaadin-grid-flow#589]
On tree grid, after calling refreshAll on data provider, grid keeps previous position. However, if refreshAll is called too frequently, tree grid cannot update the hierarchy correctly. 

**Example**

	private TreeDataProvider<Bean> provider;

	public MainView() {
		TextField field = new TextField();
		initializeDataProvider();
		field.setValueChangeMode(ValueChangeMode.EAGER);
		field.addValueChangeListener(evt -> provider.refreshAll());
		field.setSizeFull();

		TreeGrid<Bean> treeGrid = new TreeGrid<>(provider);
		treeGrid.addHierarchyColumn(Bean::getValue).setHeader("Bean");

		add(field, treeGrid);
	}

	private void initializeDataProvider() {
		TreeData<Bean> treeData = new TreeData<>();
		List<Bean> rootItems = generateChildren(null);
		treeData.addRootItems(rootItems);
		rootItems.forEach(parent -> {
			List<Bean> children = generateChildren(parent);
			treeData.addItems(parent, children);
			children.forEach(child -> treeData.addItems(child, generateChildren(child)));
		});
		provider = new TreeDataProvider<>(treeData);
	}

	private List<Bean> generateChildren(Bean bean) {
		String base = bean != null ? bean.getValue() + "." : "";
		List<Bean> beans = new ArrayList<>();
		for (int i = 0; i < 5; i++) {
			beans.add(new Bean(base + i));
		}
		return beans;
	}

**Screen recording**

![tree-grid-problem](https://user-images.githubusercontent.com/33827141/54361938-c06a8a80-4670-11e9-8fd9-664c8307cc37.gif)

Vaadin version : 13.0.1
Browser : Chrome Version 72

**Comment by pekam** [comment]
When TreeGrid has expanded nodes and `refreshAll` is called, it doesn't send all the data in the first response. It sends only the root-level items to the client, after which the client requests children of the expanded nodes. This continues recursively for the expanded children.

Because the `refreshAll` request is not handled in one roundtrip but multiple of those, it is possible to trigger `refreshAll` another time while the first recursive refreshing of the tree is still in progress.

When doing this kind of double-refresh, the subcache-request coming from the second refresh is answered directly from the grid connector's cache, as can be seen [here](https://github.com/vaadin/vaadin-grid-flow/blob/f41d74e8f7ec6c4d809d0887bc69bba3a4b58b8f/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L382). But it takes the size parameter from the grid's item-cache, which has been reset to empty one, causing the subcache to get `size = 0`. It's not correct to ask the data from one cache (connector) and the size of the data from another (`vaadin-grid`).

I'm working on a fix that adds the subcache size to the connector's cache. This way that callback can use the cached items and size from the same source.
