### ISSUE TITLE
setClassNameGenerator - class names lost after changing view

### ISSUE THREAD

**Issue by CookedApps** [vaadin/vaadin-grid-flow#684]
Hello,
we use `setClassNameGenerator` for adding a CSS class name to every cell in a specific column. This works fine when entering the corresponding view for the first time. However when navigating out of the view into another view and then going back to your grid view, the class names are missing.

```java
grid.addComponentColumn(this::getMyColumn()
        ...
        .setClassNameGenerator(tr -> "fullsize");
```

**Steps to reproduce:**
Given: _View A_ with a grid with `setClassNameGenerator` and _View B_ with something else.
- Enter _View A_ (generated class names should be present)
- Enter _View B_
- Enter _View A_ again (class names are gone now)
- Reload the page and the class names are present again

**Environment:**
- Linux Mint 19
- Chromium 75
- Vaadin 13.0.8
- vaadin-grid-flow 3.0.4

**Comment by pekam** [comment]
Thanks for filing the issue!

One clarification: Based on the description it sounds like this happens when navigating to another Flow view (annotated with `@Route`) and back, but this is basically the same as refreshing the page and doesn't reproduce the issue. The issue can be reproduced by detaching and reattaching the grid in one view.

Only column-specific styles are lost (`Column::setClassNameGenerator`), styles set with `grid.setClassNameGenerator` still work.
