### ISSUE TITLE
Grid multiselect is broken

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid-flow#73]
If you have a large multi-select grid, then clicking on the "select all" button will most of the time crash the server.

`AbstractGridMultiSelectionModel.clientSelectAll()` does a query for items 0 - 2147483646 from the data source. This should not be done.

* For a real grid, it will load the whole database table into memory, potentially millions of rows
* For a grid with generated items, it will generate 2 147 483 646 items in memory. That is 2GB * size of an item

**Comment by pleku** [comment]
This should be handled in a similar way as in V8.

**Comment by pleku** [comment]
If changing the show select all checkbox mode does not work after the grid has been rendered, create an issue for vaadin-grid.

**Comment by gilberto-torrezan** [comment]
The problem happens when the Grid's DataProvider is `isMemory`  at least once. For example, when using this code, the `selectAll` button is never shown:

```
Grid<String> grid = new Grid<>();
grid.setSelectionMode(SelectionMode.MULTI);
grid.addColumn(ValueProvider.identity());

// backend DataProvider
grid.setDataProvider(new CallbackDataProvider<>(this::fetch, this::count));
```
... but, if we set an `inMemory` DataProvider once, then the `selectAll` checkbox is presented in the component, and clicking on it can lead to `OutOfMemoryError` on the server:

```
Grid<String> grid = new Grid<>();
grid.setSelectionMode(SelectionMode.MULTI);
grid.addColumn(ValueProvider.identity());

/ /in-memory DataProvider
grid.setItems(Arrays.asList("Item 1", "Item 2", "Item 3"));

// backend DataProvider
grid.setDataProvider(new CallbackDataProvider<>(this::fetch, this::count));
```

So the bug here is: the `selectAll` checkbox is presented in the UI when an in-memory DataProvider is used, an it's never removed when a backend DataProvider is set.

**Comment by gilberto-torrezan** [comment]
As a second bug on top of this one - when the `selectAll` button is removed from the interface, it is not actually _removed_ - it is just set as hidden. The user can change its state on the browser and click on it, making the server explode once again.
