### ISSUE TITLE
Multiple rows can be selected in a single select grid using JS API

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid-flow#75]
If you do e.g.
```
$0.parentElement.selectItem($0.assignedSlot.parentElement.parentElement._item)
```
on a single select grid when a `vaadin-grid-cell-content` element is selected in the inspector, you will select the given row in addition to a previously selected row. `selectedItems` will then contain two items in a "single-select" grid.

Expected would be that the old selection is changed into the new one.

A workaround would be to use 
```
$0.parentElement.activeItem = $0.assignedSlot.parentElement.parentElement._item
```
instead but there does not seem to be any way to know if the grid is in single or multi select mode

**Comment by pleku** [comment]
What is the goal here in terms of `Grid` component ? How are you using it and what you're trying to achieve ? Why are you doing this ?

To me this looks more related to the `vaadin-grid` element and how it works on client side.
If the issue is with a `Grid` id mapped on server side to single/multi selection and it is not working in a template as you assume -> that is not supported now, and is a known limitation. We have no plans to fix that.
