### ISSUE TITLE
TreeGrid: Drag&Drop of (last?) leaf causes leafs in target node to disappear (client-side?)

### ISSUE THREAD

**Issue by KiteDX** [vaadin/vaadin-grid-flow#851]
Tested on Vaadin 14.1.2:

I made a small test project to play around with the Drag&Drop functionality of the TreeGrid, especially in combination with a custom HierarchicalDataProvider, that extracts the data to display directly from our business objects.
The server side runs fine and the expected methods and return values show up in the debugger, but I found a strange behaviour on the client side:

![Tree2](https://user-images.githubusercontent.com/24498956/70808949-1f585e00-1dc1-11ea-94c3-33ac30a8fc90.gif)

In some cases (mostly when the last leaf of a node gets dragged into another node) an expandable node seems to misbehave on the client side and doesn't appear to show its children.

Checking this in the browser networking tools shows that the info is indeed requested from the server (the respective methods of the dataprovider are called and the correct children are beeing returned) and sent to the client (see image below), but even though the node shows up as expanded, its children are missing.
![image](https://user-images.githubusercontent.com/24498956/70809418-069c7800-1dc2-11ea-9dad-bf32a53f5174.png)

A simple piece of example code to reproduce this can be found here:
https://github.com/KiteDX/Vaadin-Grid-DragAndDrop

**Comment by Haprog** [comment]
Thanks for a great reproduction code!

I checked that this can be reproduced with Vaadin 14.1.2 and also with 14.1.17, but it does not reproduce anymore with Vaadin 14.1.18 (which was just released about an hour ago).

Vaadin 14.1.2 and 14.1.17 both used vaadin-grid 5.5.0 and vaadin-grid-flow 4.1.0.  
Vaadin 14.1.18 has updated to vaadin-grid 5.5.2 and vaadin-grid-flow 4.1.3.

I did a bit more testing to check which fix actually fixed this issue and it seems that this behaviour was fixed by this PR: https://github.com/vaadin/vaadin-grid/pull/1694 which got released in vaadin-grid 5.5.2.

Closing as fixed. If you can still reproduce this with Vaadin 14.1.18 please provide additional details and we may reopen the issue.

**Comment by KiteDX** [comment]
Yeah, I can confirm that this fixed the problem :)
