### ISSUE TITLE
Column display E-notation on large numeric values

### ISSUE THREAD

**Issue by allenvpn312** [vaadin/vaadin-grid-flow#854]
Grid column displays value in E notation on large numeric value.  I believe I posted the same issue for ver 13.

`grid.addColumn(new NumberRenderer<>(FilingSummary::getSummaryValue, NumberFormat.getIntegerInstance()))
					.setHeader("Ending Inventory").setAutoWidth(true);`
![Capture](https://user-images.githubusercontent.com/9533785/71058527-c02e7c80-2125-11ea-83d8-0dc91ca46d60.PNG)

**Comment by Legioth** [comment]
The value shown in the Grid column in this case should be whatever is returned by `NumberFormat.getIntegerInstance().format(number)`. At least based on my limited testing, this doesn't lead to scientific notation with numbers in that size range on my machine.

I also couldn't reproduce the issue with this simple end-to-end example:
```
Grid<Integer> grid = new Grid<Integer>();
grid.setItems(IntStream.iterate(12, i -> i * 10).limit(9).mapToObj(Integer::valueOf));

grid.addColumn(new NumberRenderer<>(value -> value, NumberFormat.getIntegerInstance()))
        .setHeader("Ending Inventory").setAutoWidth(true);

add(grid);
```

The one way that I'm aware of that can give similar results that you reported is if the value is formatted using `Double.toString` instead of using a `NumberFormat`. `NumberFormat` can also be configured to do something similar, but I cannot make that happen with `getIntegerInstance()`.

The three potential causes that I could imagine are
1. The combination of Java installation and default locale that you're using has different defaults for how `NumberFormat.getIntegerInstance()` behaves. You can easily verify this by checking what is produced by `NumberFormat.getIntegerInstance().format(someFilingSummary.getSummaryValue())`
2. The example code that you show for configuring the grid column isn't what is actually used. There may e.g. be some additional logic that replaces or reconfigures the column before it is actually used. You can (to some degree) check if this is the case by replacing `FilingSummary::getSummaryValue` with some dummy value provider such as `ignore -> 42` and verifying that the rendered value is actually updated.
3. There's some edge case in `NumberRenderer` that isn't triggered in the simple case I tried. You can potentially trace down this by setting a breakpoint in `NumberRenderer.getFormattedValue` and checking what it does or by creating an anonymous subclass of `NumberRenderer` with `getFormattedValue` overridden to log the formatted value that it returns.

**Comment by allenvpn312** [comment]
I changed it to NumberFormat.getIntegerInstance(Locale.US) and it is working correctly.  I will check my setup to see why it did not work prior...thanks.
